language: node_js

node_js:
  - "10"

jobs:
  include:
    - stage: Builds
      script:
        - npm install
        - npm run bs
        - npm run build
      after_success:
        - ./bin/surge-deploy.sh

notifications:
  email:
    - shun10116@gmail.com
  slack:
    rooms:
      - hi-cordworkspace:EC6Q4SIRTddzUEE0rMDXrSl6#dev-travis
