language: node_js

node_js:
  - "10"

before_install:
  - npm install
  - npm run bs

jobs:
  include:
    ## TODO: Fix test error
    # - stage: Tests
    #   script: npm run test
    - stage: Builds
      script: npm run build
      after_success:
        - ./bin/surge-deploy.sh

notifications:
  email:
    - shun10116@gmail.com
  slack:
    rooms:
      - hi-cordworkspace:EC6Q4SIRTddzUEE0rMDXrSl6#dev-travis
