language: node_js

node_js:
  - '10'

branches:
  only:
    - master
    - develop
    - /^release/.*$/
    - /^synk/.*$/

install:
  - npm install

jobs:
  include:
    - stage: Component Build
      script:
        - npm run bs
        - npm run lint
        - npm run test
        - npm run build

    - stage: Docs Build
      name: Storybook build & deploy
      script:
        - npm run docs:build
      after_success: ./bin/surge-deploy.sh

notifications:
  email:
    - shun10116@gmail.com
  slack:
    rooms:
      - hi-cordworkspace:EC6Q4SIRTddzUEE0rMDXrSl6#dev-travis
