language: node_js

node_js:
  - '10'

branches:
  only:
    - master
    - develop
    - /^release/.*$/
    - /^feature/.*$/
    - /^synk/.*$/

install:
  - npm ci

script:
  - npm run bs
  - npm run lint
  - npm run test
  - npm run build

after_success:
  - ./bin/build-deploy-docs.sh

notifications:
  email:
    - shun10116@gmail.com
  slack:
    rooms:
      - hi-cordworkspace:EC6Q4SIRTddzUEE0rMDXrSl6#dev-travis
