language: node_js

node_js:
  - "12"
  - "11"
  - "10"

branches:
  only:
    - master
    - develop
    - /^greenkeeper/.*$/

install:
  - npm ci

script:
  - npm run bs
  - npm run lint
  - npm run test
  - npm run build

deploy:
  - provider: script
    script: ./bin/surge-deploy.sh

notifications:
  email:
    - shun10116@gmail.com
  slack:
    rooms:
      - hi-cordworkspace:EC6Q4SIRTddzUEE0rMDXrSl6#dev-travis
