sudo: required

language: node_js

node_js:
  - "10"

before_install:
  - yarn install
  - yarn bootstrap

cache:
  npm: true
  directories:
    - "node_modules"

jobs:
  include:
    - stage: Tests
      script: yarn test

    - stage: Builds
      script: yarn build

    - stage: Deploys
      script: ./bin/surge-deploy.sh
