version: 2
jobs:
  build:
    branches:
      only:
        - master
        - develop
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: "Checking versions"
          command: |
            node --version
            npm --version
            yarn --version

      - run:
          name: "install packages"
          command: yarn install

      - run:
          name: "Lerna bootstrap packages"
          command: yarn bs

      - run:
          name: "Lerna packages bundling"
          command: yarn bundle

      - run:
          name: "Deploy examples into surge"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn deploy:ex
            fi
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              yarn deploy:ex:dev
            fi

      - run:
          name: "Deploy docs into surge"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn deploy:docs
            fi
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              yarn deploy:docs:dev
            fi

      # - run:
      #     name: "Deploy Localize-Components into surge"
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #         yarn deploy:h
      #       fi
      #       if [ "${CIRCLE_BRANCH}" == "develop" ]; then
      #         yarn deploy:h:dev
      #       fi

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

          # - run:
      #     name: "Test using jest"
      #     command: yarn test
