version: 2.0
jobs:
  build:
    docker:
      - image: node:10.16.2-stretch
    working_directory: ~/localize-components
    branches:
      only:
        - master
        - develop
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-dependencies-{{ checksum "package.json" }}
            - node-dependencies-

      - run:
          name: "Checking versions"
          command: |
            node --version
            npm --version
            yarn --version

      # NPM process oorder : install > prepare > build
      - run:
          name: "install packages"
          command: yarn install

      - save_cache:
          key: node-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: "Buuild packages"
          command: yarn build

      # - run:
      #     name: "Publish packages into npm"
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #         yarn release:patch
      #       fi

      - run:
          name: "Deploy docs into surge"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn deploy:docs
            fi
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              yarn deploy:docs:dev
            fi

      - run:
          name: "Deploy examples into surge"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn deploy:ex
            fi
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              yarn deploy:ex:dev
            fi
