version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version

      - run:
          name: "install packages"
          command: yarn install

      - run:
          name: "Lerna Bootstrap packages"
          command: yarn bundle

      - run:
          name: "Deploy Examples into surge"
          command: yarn deploy:ex

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

          # - run:
      #     name: "Test using jest"
      #     command: yarn test
