version: 2
jobs:
  build:
    branches:
      only:
        - master
        - develop
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version

      - run:
          name: "Lerna Install Packages"
          command: yarn bs

      - run:
          name: "Lerna Packages Build"
          command: yarn packages:build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # - run:
      #     name: "Test using jest"
      #     command: yarn test
